# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/file_server.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/file_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/file_server.proto\"\t\n\x07GetList\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\")\n\x14\x44ownloadFileResponse\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\"R\n\x11UploadFileRequest\x12\x1d\n\x08metadata\x18\x01 \x01(\x0b\x32\t.MetaDataH\x00\x12\x13\n\tfile_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request2\x92\x01\n\x07Greeter\x12$\n\x0bGetFileList\x12\x08.GetList\x1a\t.Response0\x01\x12-\n\nUploadFile\x12\x12.UploadFileRequest\x1a\t.Response(\x01\x12\x32\n\x0c\x44ownloadFile\x12\t.MetaData\x1a\x15.DownloadFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.file_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLIST']._serialized_start=27
  _globals['_GETLIST']._serialized_end=36
  _globals['_RESPONSE']._serialized_start=38
  _globals['_RESPONSE']._serialized_end=65
  _globals['_METADATA']._serialized_start=67
  _globals['_METADATA']._serialized_end=95
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=97
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=138
  _globals['_UPLOADFILEREQUEST']._serialized_start=140
  _globals['_UPLOADFILEREQUEST']._serialized_end=222
  _globals['_GREETER']._serialized_start=225
  _globals['_GREETER']._serialized_end=371
# @@protoc_insertion_point(module_scope)
